name: CI

on: ["push", "pull_request"]

jobs:
  ci:
    name: ci
    strategy:
      fail-fast: false
      matrix:
        #os: ["windows-latest", "ubuntu-latest", "macOS-latest"]
        os: ["ubuntu-latest"]
        go: ["1.20.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{ matrix.go }}
      - name: Install Dependecies
        run: sudo apt-get install -y libpcap-dev
        if: matrix.os == 'ubuntu-latest'
      - run: "go test ./..."
      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          install-go: false
          cache-key: ${{ matrix.go }}